# Generated by Django 5.2 on 2025-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='language',
            field=models.CharField(default='English'),
        ),
        migrations.AddField(
            model_name='idiom',
            name='related',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.CharField(default='English'),
        ),
        migrations.AlterField(
            model_name='idiom',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
