# Generated by Django 5.2 on 2025-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiom',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
